# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d65e9512274484466012861cc6422dc6d8aa9c56f79df8858dc99dc56aa0e4a1349b5e814bf79424b231b554952005c583779a614c0b1c5e7b4b6de417f43230

test:
  secret_key_base: 7a52193a739e819ff1f483e015f2a38a1994bd9b136e26a466e3a199b40d64f8c1b88910889fbe354165db989bcb13cd46e21a88744daf909347890c2a6796d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
